--5. SYSDATE: VALOR DE LA FECHA ACTUAL
SELECT SYSDATE FROM EMPLEADO;

--5.1. SYSTIMESTAMP: VALOR DE LA FECHA Y HORA
SELECT SYSTIMESTAMP FROM EMPLEADO;

--5.2  ADD_MONTHS: AÑADE MESES DESDE UNA FECHA DADA
SELECT ADD_MONTHS(SYSDATE,2) FROM EMPLEADO;

--5.3 MONTHS BETWEEN: NOS DICE LOS MESES QUE HAY ENTRE FECHA A Y B
SELECT MONTHS_BETWEEN(ADD_MONTHS(SYSDATE,5), SYSDATE) FROM EMPLEADO;

--5.4 NEX_DAY/LAST_DAY: SIGUIENTE DIA Y ULTIMO DIA DEL MES (1->lunes, 2->martes, 3->miercoles .. etc) 
SELECT NEXT_DAY(SYSDATE,5) FROM EMPLEADO;
SELECT LAST_DAY(SYSDATE) FROM EMPLEADO;

--5.5 EXTRACT DEVUELVE EL VALOR DE UNA FECHA CONCRETA
SELECT EXTRACT(DAY FROM SYSDATE) FROM EMPLEADO;
SELECT EXTRACT(MONTH FROM SYSDATE) FROM EMPLEADO;