--4. FUNCIONES DE CADENAS
--4.1 CHR: DEVUELVE EL VALOR CODIFICADO DE UN NÚMERO
SELECT CHR(1) FROM EMPLEADO;

--4.2 ASCII: DEVUELVE EL VALOR ASCII
SELECT ASCII('o') FROM EMPLEADO;

--4.3 CONCAT: CONCATENA CADENAS, IGUAL QUE ||
SELECT CONCAT('Adrian',' Pueyo') FROM EMPLEADO;

--4.4 LOWER/UPPER: DEVULVEN LOS VALORES EN MINUCULAS O MAYUSCULAS
SELECT LOWER('ABC') FROM EMPLEADO;
SELECT UPPER('abc') FROM EMPLEADO;

--4.5 INITCAP: DEVUELVE EL VALOR CON LA PRIMERA LETRA EN MAYUSCULAS
SELECT INITCAP('adri') FROM EMPLEADO;

--4.6 LPAD/RPAD: RELLENA UN VALOR A IZQUIERDA O DERECHA(ej: ****A A****)
SELECT LPAD('A', 5, '****') FROM EMPLEADO;
SELECT RPAD('A', 5, '****') FROM EMPLEADO;

--4.7 REPLACE; REEMPLAZA UN VALOR POR OTRO
SELECT REPLACE('test@gmail.es', 'es', 'com') FROM EMPLEADO;

--4.8 SUBSTR: DEVUELVE UNA PARTE DE UNA CADENA
SELECT SUBSTR('1234567', 2,3) FROM EMPLEADO;

--4.9 LENGTH: DEVUELVE LA LONGITUD DE UNA CADENA(o de varias)
SELECT LENGTH(NOMBRE) FROM EMPLEADO;

--4.10 TRIM/LTRIM/RTRIM: ELMINA ESPACIOS EN BLANCO A LA DERECHA E IZQUIERDA 
SELECT TRIM(' a a ') FROM EMPLEADO;
SELECT LTRIM(' a a ') FROM EMPLEADO;
SELECT RTRIM(' a a ') FROM EMPLEADO;