-- 2. OPERADORES
-- 2.1.1 OPERADORES DE COMPARACIÓN NUMBERS: - =  >  <  

SELECT NOMBRE FROM EMPLEADO WHERE coddpto = 01;
SELECT NOMBRE FROM EMPLEADO WHERE salario>2000;

-- 2.1.2 OPERADORES DE COMPRACIÓN STRING: LIKE
SELECT NOMBRE FROM EMPLEADO WHERE ape1 LIKE 'LOPEZ%';

--2.2 OPERADORES ARITMETICOS: * - + /
-- CON AS ELEGIMOS COMO MOSTRAMOS EL CAMPO EN LA TABLA FINAL
SELECT NOMBRE, SALARIO*1.05 AS "SALARIO CON PLUS" FROM EMPLEADO;

--2.3 OPERADORES DE CONCATENACIÓN: ||
-- CON ESTE OPERADOR PODEMOS JUNTAR DOS CAMPOS 
SELECT NOMBRE, APE1 || ' ' || APE2 FROM EMPLEADO;

--2.4 OPERADORES DE COMPARACIÓN: AND OR NOT
SELECT NOMBRE, SALARIO FROM EMPLEADO WHERE SALARIO>2000 AND SALARIO<3000;
SELECT NOMBRE, SALARIO FROM EMPLEADO WHERE SALARIO=2000 OR SALARIO=3000;