-- 1. SELECT BÁSICO

SELECT NOMBRE FROM EMPLEADO;

-- 1.1 SELECT + PERSONALIZACIÓN

SELECT NOMBRE, SALARIO "Cobra: " FROM EMPLEADO;

-- 1.2 SELECT + WHERE

SELECT NOMBRE, SALARIO FROM EMPLEADO WHERE SALARIO>2000;

-- 1.3 SELECT + ORDER (ORDENADO ALFABÉTICO)

SELECT NOMBRE FROM EMPLEADO ORDER BY NOMBRE;

-- 1.4 SELECT + ORDER (ORDENADO MAYOR A MENOR CON DESC)

SELECT NOMBRE, SALARIO FROM EMPLEADO WHERE SALARIO>2000 ORDER BY SALARIO DESC;

-- 1.5 SELECT + ORDER (ORDENADO MENOR A MAYOR CON ASC)

SELECT NOMBRE, SALARIO FROM EMPLEADO WHERE SALARIO>2000 ORDER BY SALARIO ASC;

